# terms to search for in the keyword approach (from NIDA guidelines)
stigmatizing_terms:
  - user
  - substance abuser
  - drug abuser
  - abuse
  - junkie
  - alcoholic
  - drunk
  - former addict
  - reformed addict
  - habit
  - abuse
  - clean
  - dirty
  - addicted baby