#!/bin/bash
deepspeed --num_gpus 8 path-to-llamafactory-train.py \
    --deepspeed path-to-configuration-deepspeed-file-ds_config.json \
    --stage sft \
    --do_train \
    --model_name_or_path path-to-directory-with-model-safe-tensors-or-model-name \
    --dataset name-of-dataset-in-llama-factory \
    --template llama3 \
    --output_dir path-to-output-directory-of-your-choice \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 500 \
    --learning_rate 0.00001 \
    --num_train_epochs 3.0 \
    --fp16 \
    --plot_loss \
    --finetuning_type lora \
    --lora_target all \
